# Generated by Django 2.1.7 on 2026-06-04 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SustainTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_no', models.CharField(max_length=50, unique=True, verbose_name='Task No')),
                ('year', models.IntegerField(choices=[(2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030'), (2031, '2031'), (2032, '2032'), (2033, '2033'), (2034, '2034'), (2035, '2035'), (2036, '2036'), (2037, '2037'), (2038, '2038'), (2039, '2039'), (2040, '2040'), (2041, '2041'), (2042, '2042'), (2043, '2043'), (2044, '2044'), (2045, '2045'), (2046, '2046'), (2047, '2047'), (2048, '2048'), (2049, '2049'), (2050, '2050'), (2051, '2051'), (2052, '2052'), (2053, '2053'), (2054, '2054'), (2055, '2055'), (2056, '2056'), (2057, '2057'), (2058, '2058'), (2059, '2059'), (2060, '2060'), (2061, '2061'), (2062, '2062'), (2063, '2063'), (2064, '2064'), (2065, '2065'), (2066, '2066'), (2067, '2067'), (2068, '2068'), (2069, '2069'), (2070, '2070'), (2071, '2071'), (2072, '2072'), (2073, '2073'), (2074, '2074'), (2075, '2075'), (2076, '2076'), (2077, '2077'), (2078, '2078'), (2079, '2079'), (2080, '2080'), (2081, '2081'), (2082, '2082'), (2083, '2083'), (2084, '2084'), (2085, '2085'), (2086, '2086'), (2087, '2087'), (2088, '2088'), (2089, '2089'), (2090, '2090'), (2091, '2091'), (2092, '2092'), (2093, '2093'), (2094, '2094'), (2095, '2095'), (2096, '2096'), (2097, '2097'), (2098, '2098'), (2099, '2099'), (2100, '2100'), (2101, '2101'), (2102, '2102'), (2103, '2103'), (2104, '2104'), (2105, '2105'), (2106, '2106')], verbose_name='Year')),
                ('month', models.CharField(choices=[('Jan', 'Jan'), ('Feb', 'Feb'), ('Mar', 'Mar'), ('Apr', 'Apr'), ('May', 'May'), ('Jun', 'Jun'), ('Jul', 'Jul'), ('Aug', 'Aug'), ('Sep', 'Sep'), ('Oct', 'Oct'), ('Nov', 'Nov'), ('Dec', 'Dec')], max_length=20, verbose_name='Month')),
                ('customer', models.CharField(choices=[('C38 NB', 'C38 NB'), ('C38 AIO', 'C38 AIO')], max_length=50, verbose_name='Customer')),
                ('series', models.CharField(blank=True, choices=[('Gaming', 'Gaming'), ('Consumer', 'Consumer'), ('SMB', 'SMB'), ('Consumer_CX', 'Consumer_CX'), ('Consumer_SX', 'Consumer_SX'), ('Consumer_SXP', 'Consumer_SXP'), ('', '----')], max_length=100, verbose_name='Series')),
                ('project_code', models.CharField(max_length=50, verbose_name='Project Code')),
                ('project_name', models.CharField(blank=True, max_length=200, verbose_name='Project Name')),
                ('mp_date', models.DateField(blank=True, null=True, verbose_name='MP Date')),
                ('eop_or_not', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=3, verbose_name='EOP Or Not')),
                ('eop_date', models.DateField(blank=True, null=True, verbose_name='EOP Date')),
                ('eos_date', models.DateField(blank=True, null=True, verbose_name='EOS Date')),
                ('project_status', models.CharField(blank=True, max_length=20, verbose_name='Project Status')),
                ('mp_year', models.CharField(blank=True, max_length=20, verbose_name='MP Year')),
                ('eop_year', models.CharField(blank=True, max_length=20, verbose_name='EOP Year')),
                ('eos_year', models.CharField(blank=True, max_length=20, verbose_name='EOS Year')),
                ('leverage_project', models.CharField(blank=True, max_length=10, verbose_name='Leverage Project')),
                ('test_units_status', models.CharField(blank=True, max_length=200, verbose_name='Test Units status')),
                ('unit_qty', models.IntegerField(default=0, verbose_name='Unit_Qty')),
                ('total_test_resource', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Test Resource')),
                ('total_actual_workload', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Actual Workload(Hrs)')),
                ('total_leverage_workload', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Leverage Workload(Hrs)')),
                ('final_test_status', models.CharField(blank=True, max_length=50, verbose_name='Final Test Status')),
                ('task_closure_date', models.DateField(blank=True, null=True, verbose_name='Task Closure Date')),
                ('task_leading_time', models.IntegerField(default=0, verbose_name='Task Leading Time (Days)')),
                ('total_planning_workload', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Planning Workload(Hrs)')),
                ('total_waste_time', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total waste time (Hrs)')),
            ],
            options={
                'verbose_name': 'Sustain Task',
                'verbose_name_plural': 'Sustain Tasks',
                'ordering': ['-year', '-task_no'],
            },
        ),
        migrations.CreateModel(
            name='SustainTestDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_stage', models.CharField(choices=[('New Test', 'New Test'), ('Regression1', 'Regression1'), ('Regression2', 'Regression2'), ('Regression3', 'Regression3'), ('Regression4', 'Regression4'), ('Regression5', 'Regression5')], max_length=20, verbose_name='Test Stage')),
                ('test_status', models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('Conditional Pass', 'Conditional Pass'), ('Planning', 'Planning'), ('Pending', 'Pending'), ('Testing', 'Testing')], max_length=50, verbose_name='Test Status')),
                ('test_category', models.CharField(blank=True, choices=[('BIOS', 'BIOS'), ('VBIOS', 'VBIOS'), ('Driver', 'Driver'), ('APP', 'APP'), ('FW', 'FW'), ('Other', 'Other')], max_length=50, verbose_name='Test Category')),
                ('category_info', models.CharField(blank=True, max_length=200, verbose_name='Category Info')),
                ('test_version', models.CharField(blank=True, max_length=100, verbose_name='Test Version')),
                ('test_condition', models.TextField(blank=True, verbose_name='Test Condition (BIOS/Image/OS)')),
                ('driver_cut_in_format', models.CharField(blank=True, max_length=200, verbose_name='Driver cut in format')),
                ('issue_link', models.URLField(blank=True, verbose_name='Issue Link')),
                ('test_resource', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Test Resource')),
                ('actual_workload', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Actual Workload(Hrs)')),
                ('leverage_workload', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Leverage Workload(Hrs)')),
                ('test_team', models.CharField(blank=True, max_length=200, verbose_name='Test Team')),
                ('test_owner', models.CharField(blank=True, max_length=100, verbose_name='Test_Owner')),
                ('test_start', models.DateField(blank=True, null=True, verbose_name='Test_Start')),
                ('test_end', models.DateField(blank=True, null=True, verbose_name='Test_End')),
                ('working_day', models.IntegerField(default=0, verbose_name='Working Day')),
                ('change_list', models.TextField(blank=True, verbose_name='Change list')),
                ('remark', models.TextField(blank=True, verbose_name='Remark')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_details', to='Sustain.SustainTask', verbose_name='所属任务')),
            ],
            options={
                'verbose_name': 'Test Detail',
                'verbose_name_plural': 'Test Details',
                'ordering': ['task', 'test_stage'],
            },
        ),
    ]
