# Generated by Django 2.1.7 on 2026-06-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sustain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sustaintask',
            name='leverage_project',
            field=models.CharField(blank=True, max_length=200, verbose_name='Leverage Project'),
        ),
        migrations.AlterField(
            model_name='sustaintestdetail',
            name='test_version',
            field=models.CharField(blank=True, max_length=200, verbose_name='Test Version'),
        ),
    ]
