# Generated by Django 2.1.7 on 2026-06-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sustain', '0002_auto_20260605_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sustaintask',
            name='project_name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='sustaintask',
            name='series',
            field=models.CharField(blank=True, choices=[('Gaming', 'Gaming'), ('Consumer', 'Consumer'), ('SMB', 'SMB'), ('Consumer_CX', 'Consumer_CX'), ('Consumer_SX', 'Consumer_SX'), ('Consumer_SXP', 'Consumer_SXP'), ('', '----')], max_length=200, verbose_name='Series'),
        ),
        migrations.AlterField(
            model_name='sustaintestdetail',
            name='category_info',
            field=models.CharField(blank=True, max_length=500, verbose_name='Category Info'),
        ),
        migrations.AlterField(
            model_name='sustaintestdetail',
            name='driver_cut_in_format',
            field=models.CharField(blank=True, max_length=500, verbose_name='Driver cut in format'),
        ),
        migrations.AlterField(
            model_name='sustaintestdetail',
            name='test_category',
            field=models.CharField(blank=True, choices=[('BIOS', 'BIOS'), ('VBIOS', 'VBIOS'), ('Driver', 'Driver'), ('APP', 'APP'), ('FW', 'FW'), ('Other', 'Other')], max_length=200, verbose_name='Test Category'),
        ),
        migrations.AlterField(
            model_name='sustaintestdetail',
            name='test_owner',
            field=models.CharField(blank=True, max_length=500, verbose_name='Test_Owner'),
        ),
        migrations.AlterField(
            model_name='sustaintestdetail',
            name='test_version',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Test Version'),
        ),
    ]
