# Generated by Django 2.1.7 on 2025-03-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlanSW', '0015_auto_20250122_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testplanswaio',
            name='Phase',
            field=models.CharField(choices=[('', ''), ('B(SDV)', 'B(SDV)'), ('FVT Regression1', 'FVT Regression1'), ('FVT Regression2', 'FVT Regression2'), ('C(SIT)', 'C(SIT)'), ('SIT Regerssion1', 'SIT Regerssion1'), ('SIT Regerssion2', 'SIT Regerssion2'), ('SIT Regerssion3', 'SIT Regerssion3'), ('SIT Regerssion4', 'SIT Regerssion4'), ('SIT Regerssion5', 'SIT Regerssion5'), ('Wave2', 'Wave2'), ('Wave3', 'Wave3'), ('EELP+', 'EELP+'), ('OOC', 'OOC'), ('OOC2', 'OOC2'), ('OOC3', 'OOC3'), ('Others', 'Others')], default='', max_length=20, verbose_name='Phase'),
        ),
        migrations.AlterField(
            model_name='testprojectswaio',
            name='Phase',
            field=models.CharField(choices=[('', ''), ('B(SDV)', 'B(SDV)'), ('FVT Regression1', 'FVT Regression1'), ('FVT Regression2', 'FVT Regression2'), ('C(SIT)', 'C(SIT)'), ('SIT Regerssion1', 'SIT Regerssion1'), ('SIT Regerssion2', 'SIT Regerssion2'), ('SIT Regerssion3', 'SIT Regerssion3'), ('SIT Regerssion4', 'SIT Regerssion4'), ('SIT Regerssion5', 'SIT Regerssion5'), ('Wave2', 'Wave2'), ('Wave3', 'Wave3'), ('EELP+', 'EELP+'), ('OOC', 'OOC'), ('OOC2', 'OOC2'), ('OOC3', 'OOC3'), ('Others', 'Others')], max_length=20, verbose_name='Phase'),
        ),
    ]
