# Generated by Django 2.1.7 on 2025-09-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlanSW', '0016_auto_20250321_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='testplansw',
            name='FeatureWeight',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='FeatureWeight'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='PhaseEVT',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('O', 'O')], default='', max_length=10, null=True, verbose_name='Develop phase(TPL) EVT'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='PhaseGO',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('O', 'O')], default='', max_length=10, null=True, verbose_name='Develop phase(TPL) G/O'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='PhaseGsku',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('O', 'O')], default='', max_length=10, null=True, verbose_name='Develop phase(TPL) Gsku'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='Remark',
            field=models.CharField(blank=True, default='', max_length=1500, null=True, verbose_name='Remark'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='RemarkforFeatureWeightadjust',
            field=models.CharField(blank=True, default='', max_length=1500, null=True, verbose_name='Remark for Feature Weight adjust(TL僅可調整且只能根據定義進行調整 feature weight，定義外的測項不可自行調整)'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='RevisedbasetimeorAttendedtime',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='Revised base time (Attended time)'),
        ),
        migrations.AlterField(
            model_name='testplansw',
            name='AttendTimeOptimize',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='Attend time-Optimize'),
        ),
        migrations.AlterField(
            model_name='testplansw',
            name='BaseAotomationTime1SKU',
            field=models.FloatField(blank=True, max_length=10, null=True, verbose_name='Base time-Automation (1SKU)'),
        ),
        migrations.AlterField(
            model_name='testplansw',
            name='BaseTime',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='TDMS Working time(Attended time)'),
        ),
        migrations.AlterField(
            model_name='testplansw',
            name='BaseTimeSupport',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='Base*Weight'),
        ),
        migrations.AlterField(
            model_name='testplansw',
            name='ConfigAutomationItem',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Y'), ('N', 'N')], default='', max_length=5, null=True, verbose_name='Config-Automation Item'),
        ),
        migrations.AlterField(
            model_name='testplansw',
            name='ConfigAutomationTime',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='Config-Automation time'),
        ),
        migrations.AlterField(
            model_name='testplansw',
            name='ConfigLeverageItem',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Y'), ('N', 'N')], default='', max_length=5, null=True, verbose_name='Config-Leverage Item'),
        ),
        migrations.AlterField(
            model_name='testplansw',
            name='ConfigLeverageTime',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='Config-Leverage time'),
        ),
        migrations.AlterField(
            model_name='testplansw',
            name='ConfigRetestCycle',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='Config-Retest Cycle'),
        ),
        migrations.AlterField(
            model_name='testplansw',
            name='ConfigRetestSKU',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='Config-Retest SKU'),
        ),
        migrations.AlterField(
            model_name='testplansw',
            name='ConfigRetestTime',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='Config-Retest time'),
        ),
        migrations.AlterField(
            model_name='testplansw',
            name='ConfigSmartItem',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Y'), ('N', 'N')], default='', max_length=5, null=True, verbose_name='Config-Smart Item'),
        ),
        migrations.AlterField(
            model_name='testplansw',
            name='ConfigSmartItemPer',
            field=models.FloatField(blank=True, max_length=10, null=True, verbose_name='Config-Smart Item占总case比例'),
        ),
        migrations.AlterField(
            model_name='testplansw',
            name='ConfigSmartTime',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='Config-Smart time'),
        ),
        migrations.AlterField(
            model_name='testplansw',
            name='ItemNo_d',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Case ID'),
        ),
        migrations.AlterField(
            model_name='testplansw',
            name='Item_d',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Case name'),
        ),
        migrations.AlterField(
            model_name='testplansw',
            name='PhaseFFRT',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('O', 'O')], default='', max_length=10, null=True, verbose_name='Develop phase(TPL) FFRT'),
        ),
        migrations.AlterField(
            model_name='testplansw',
            name='PhaseFVT',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('O', 'O')], default='', max_length=10, null=True, verbose_name='Develop phase(TPL) FVT'),
        ),
        migrations.AlterField(
            model_name='testplansw',
            name='PhaseSIT',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('O', 'O')], default='', max_length=10, null=True, verbose_name='Develop phase(TPL) SIT'),
        ),
        migrations.AlterField(
            model_name='testplansw',
            name='ProjectTestSKUOptimize',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='Project test SKU-Optimize'),
        ),
        migrations.AlterField(
            model_name='testplansw',
            name='ProjectTestSKUfollowMatrix',
            field=models.FloatField(blank=True, max_length=10, null=True, verbose_name='Project test SKU-follow matrix'),
        ),
        migrations.AlterField(
            model_name='testplansw',
            name='ReleaseDate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Release date'),
        ),
        migrations.AlterField(
            model_name='testplansw',
            name='TDMSTotalTime',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='TDMS Leading Time (A+U)'),
        ),
        migrations.AlterField(
            model_name='testplansw',
            name='TDMSUnattendedTime',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='(TDMS) Unattended  time'),
        ),
        migrations.AlterField(
            model_name='testplansw',
            name='TestItems',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Test Items'),
        ),
        migrations.AlterField(
            model_name='testplansw',
            name='TimewConfigFollowmatrix',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='Time w/ Config-follow matrix'),
        ),
    ]
