# Generated by Django 2.1.7 on 2025-09-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlanSW', '0017_auto_20250903_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='retestitemsw',
            name='FeatureWeight',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='FeatureWeight'),
        ),
        migrations.AddField(
            model_name='retestitemsw',
            name='PhaseEVT',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('O', 'O')], default='', max_length=10, null=True, verbose_name='Develop phase(TPL) EVT'),
        ),
        migrations.AddField(
            model_name='retestitemsw',
            name='PhaseGO',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('O', 'O')], default='', max_length=10, null=True, verbose_name='Develop phase(TPL) G/O'),
        ),
        migrations.AddField(
            model_name='retestitemsw',
            name='PhaseGsku',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('O', 'O')], default='', max_length=10, null=True, verbose_name='Develop phase(TPL) Gsku'),
        ),
        migrations.AddField(
            model_name='retestitemsw',
            name='Remark',
            field=models.CharField(blank=True, default='', max_length=1500, null=True, verbose_name='Remark'),
        ),
        migrations.AddField(
            model_name='retestitemsw',
            name='RemarkforFeatureWeightadjust',
            field=models.CharField(blank=True, default='', max_length=1500, null=True, verbose_name='Remark for Feature Weight adjust(TL僅可調整且只能根據定義進行調整 feature weight，定義外的測項不可自行調整)'),
        ),
        migrations.AddField(
            model_name='retestitemsw',
            name='RevisedbasetimeorAttendedtime',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='Revised base time (Attended time)'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='AttendTimeOptimize',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='Attend time-Optimize'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='BaseAotomationTime1SKU',
            field=models.FloatField(blank=True, max_length=10, null=True, verbose_name='Base time-Automation (1SKU)'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='BaseTime',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='TDMS Working time(Attended time)'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='BaseTimeSupport',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='Base*Weight'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='Category',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='Category2',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Category2'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='Chramshell',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('O', 'O')], default='', max_length=10, null=True, verbose_name='Chramshell'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='CommentsLeverage',
            field=models.CharField(blank=True, default='', max_length=1500, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='CommentsSmart',
            field=models.CharField(blank=True, default='', max_length=1500, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='ConfigAutomationItem',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Y'), ('N', 'N')], default='', max_length=5, null=True, verbose_name='Config-Automation Item'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='ConfigAutomationTime',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='Config-Automation time'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='ConfigLeverageItem',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Y'), ('N', 'N')], default='', max_length=5, null=True, verbose_name='Config-Leverage Item'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='ConfigLeverageTime',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='Config-Leverage time'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='ConfigRetestCycle',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='Config-Retest Cycle'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='ConfigRetestSKU',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='Config-Retest SKU'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='ConfigRetestTime',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='Config-Retest time'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='ConfigSmartItem',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Y'), ('N', 'N')], default='', max_length=5, null=True, verbose_name='Config-Smart Item'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='ConfigSmartItemPer',
            field=models.FloatField(blank=True, max_length=10, null=True, verbose_name='Config-Smart Item占总case比例'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='ConfigSmartTime',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='Config-Smart time'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='ConvertibaleNBMode',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('O', 'O')], default='', max_length=10, null=True, verbose_name='ConvertibaleNBMode'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='ConvertibaleYogaPadMode',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('O', 'O')], default='', max_length=10, null=True, verbose_name='ConvertibaleYogaPadMode'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='Coverage',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Coverage'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='Customer',
            field=models.CharField(choices=[('', ''), ('C38(NB)', 'C38(NB)'), ('C38(NB)-SMB', 'C38(NB)-SMB'), ('C38(AIO)', 'C38(AIO)'), ('T88(AIO)', 'T88(AIO)'), ('A39', 'A39'), ('C85', 'C85'), ('Others', 'Others')], default='C38(NB)', max_length=20, verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='DetachablePadMode',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('O', 'O')], default='', max_length=10, null=True, verbose_name='DetachablePadMode'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='DetachableWDockmode',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('O', 'O')], default='', max_length=10, null=True, verbose_name='DetachableWDockmode'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='FeatureSupport',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Y'), ('N', 'N')], default='', max_length=5, null=True, verbose_name='FeatureSupport'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='ItemNo_d',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Case ID'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='Item_d',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Case name'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='Owner',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='Phase',
            field=models.CharField(choices=[('', ''), ('B(FVT)', 'B(FVT)'), ('FVT Regression1', 'FVT Regression1'), ('FVT Regression2', 'FVT Regression2'), ('C(SIT)', 'C(SIT)'), ('SIT2', 'SIT2'), ('SIT Regerssion1', 'SIT Regerssion1'), ('SIT Regerssion2', 'SIT Regerssion2'), ('SIT Regerssion3', 'SIT Regerssion3'), ('SIT Regerssion4', 'SIT Regerssion4'), ('SIT Regerssion5', 'SIT Regerssion5'), ('GSKU', 'GSKU'), ('Downgrade', 'Downgrade'), ('Wave', 'Wave'), ('Wave2', 'Wave2'), ('Wave3', 'Wave3'), ('Wave4', 'Wave4'), ('Wave5', 'Wave5'), ('OOC', 'OOC'), ('OOC2', 'OOC2'), ('OOC3', 'OOC3'), ('OOC4', 'OOC4'), ('OOC5', 'OOC5'), ('OOC6', 'OOC6'), ('FFRT', 'FFRT'), ('FFRT2', 'FFRT2'), ('FFRT3', 'FFRT3'), ('FFRT4', 'FFRT4'), ('FFRT5', 'FFRT5'), ('FFRT6', 'FFRT6'), ('SIT_U9', 'SIT_U9'), ('U9_FFRT', 'U9_FFRT'), ('U9_FFRT2', 'U9_FFRT2'), ('U9_FFRT3', 'U9_FFRT3'), ('GSKU_FFRT', 'GSKU_FFRT'), ('GSKU_FFRT2', 'GSKU_FFRT2'), ('GSKU_FFRT3', 'GSKU_FFRT3'), ('DG_FFRT', 'DG_FFRT'), ('DG_FFRT2', 'DG_FFRT2'), ('DG_FFRT3', 'DG_FFRT3'), ('Others', 'Others')], default='', max_length=20, verbose_name='Phase'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='PhaseFFRT',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('O', 'O')], default='', max_length=10, null=True, verbose_name='Develop phase(TPL) FFRT'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='PhaseFVT',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('O', 'O')], default='', max_length=10, null=True, verbose_name='Develop phase(TPL) FVT'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='PhaseSIT',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('O', 'O')], default='', max_length=10, null=True, verbose_name='Develop phase(TPL) SIT'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='Priority',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='ProjectTestSKUOptimize',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='Project test SKU-Optimize'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='ProjectTestSKUfollowMatrix',
            field=models.FloatField(blank=True, max_length=10, null=True, verbose_name='Project test SKU-follow matrix'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='ReleaseDate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Release date'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='SKU1',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU1'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='SKU10',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU10'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='SKU11',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU11'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='SKU12',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU12'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='SKU13',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU13'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='SKU14',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU14'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='SKU15',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU15'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='SKU16',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU16'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='SKU17',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU17'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='SKU18',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU18'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='SKU19',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU19'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='SKU2',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU2'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='SKU20',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU20'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='SKU21',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU21'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='SKU22',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU22'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='SKU23',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU23'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='SKU24',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU24'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='SKU25',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU25'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='SKU26',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU26'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='SKU27',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU27'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='SKU28',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU28'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='SKU29',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU29'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='SKU3',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU3'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='SKU30',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU30'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='SKU31',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU31'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='SKU32',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU32'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='SKU33',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU33'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='SKU34',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU34'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='SKU35',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU35'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='SKU36',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU36'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='SKU37',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU37'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='SKU38',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU38'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='SKU39',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU39'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='SKU4',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU4'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='SKU40',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU40'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='SKU5',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU5'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='SKU6',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU6'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='SKU7',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU7'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='SKU8',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU8'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='SKU9',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU9'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='Schedule',
            field=models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='Schedule'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='TDMSTotalTime',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='TDMS Leading Time (A+U)'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='TDMSUnattendedTime',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='(TDMS) Unattended  time'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='TE',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='TE'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='TestItems',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Test Items'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='TimewConfigFollowmatrix',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='Time w/ Config-follow matrix'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='Version',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='edit_time',
            field=models.CharField(blank=True, default='', max_length=26, null=True, verbose_name='edit_time'),
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='editor',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='editor'),
        ),
    ]
