# Generated by Django 2.1.7 on 2026-04-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlanSW', '0022_auto_20260417_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='testplanswaio',
            name='BaseTimeWeight',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='Base Time*Weight'),
        ),
        migrations.AddField(
            model_name='testplanswaio',
            name='ItemNo_d',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Case ID'),
        ),
        migrations.AddField(
            model_name='testplanswaio',
            name='Weight',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='testprojectsw',
            name='Phase',
            field=models.CharField(choices=[('', ''), ('B(FVT)', 'B(FVT)'), ('FVT Regression1', 'FVT Regression1'), ('FVT Regression2', 'FVT Regression2'), ('FVT Regression3', 'FVT Regression3'), ('FVT Regression4', 'FVT Regression4'), ('FVT Regression5', 'FVT Regression5'), ('FVT Regression6', 'FVT Regression6'), ('FVT Regression7', 'FVT Regression7'), ('FVT Regression8', 'FVT Regression8'), ('C(SIT)', 'C(SIT)'), ('SIT2', 'SIT2'), ('SIT Regerssion1', 'SIT Regerssion1'), ('SIT Regerssion2', 'SIT Regerssion2'), ('SIT Regerssion3', 'SIT Regerssion3'), ('SIT Regerssion4', 'SIT Regerssion4'), ('SIT Regerssion5', 'SIT Regerssion5'), ('SIT Regerssion6', 'SIT Regerssion6'), ('SIT Regerssion7', 'SIT Regerssion7'), ('SIT Regerssion8', 'SIT Regerssion8'), ('GSKU', 'GSKU'), ('Downgrade', 'Downgrade'), ('Wave', 'Wave'), ('Wave2', 'Wave2'), ('Wave3', 'Wave3'), ('Wave4', 'Wave4'), ('Wave5', 'Wave5'), ('OOC', 'OOC'), ('OOC2', 'OOC2'), ('OOC3', 'OOC3'), ('OOC4', 'OOC4'), ('OOC5', 'OOC5'), ('OOC6', 'OOC6'), ('FFRT', 'FFRT'), ('FFRT2', 'FFRT2'), ('FFRT3', 'FFRT3'), ('FFRT4', 'FFRT4'), ('FFRT5', 'FFRT5'), ('FFRT6', 'FFRT6'), ('SIT_U9', 'SIT_U9'), ('U9_FFRT', 'U9_FFRT'), ('U9_FFRT2', 'U9_FFRT2'), ('U9_FFRT3', 'U9_FFRT3'), ('GSKU_FFRT', 'GSKU_FFRT'), ('GSKU_FFRT2', 'GSKU_FFRT2'), ('GSKU_FFRT3', 'GSKU_FFRT3'), ('DG_FFRT', 'DG_FFRT'), ('DG_FFRT2', 'DG_FFRT2'), ('DG_FFRT3', 'DG_FFRT3'), ('Others', 'Others')], max_length=20, verbose_name='Phase'),
        ),
    ]
