# Generated by Django 2.1.7 on 2026-04-23 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlanSW', '0023_auto_20260423_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testplanswaio',
            old_name='ItemNo_d',
            new_name='Case_ID',
        ),
    ]
