# Generated by Django 2.1.7 on 2026-06-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlanSW', '0028_auto_20260526_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='retestitemsw',
            name='Attention',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Attention'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='Attention',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Attention'),
        ),
    ]
