# Generated by Django 2.1.7 on 2026-06-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlanSW', '0032_auto_20260623_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='retestitemsw',
            name='bios',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='BIOS'),
        ),
        migrations.AddField(
            model_name='retestitemsw',
            name='ee',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='EE'),
        ),
        migrations.AddField(
            model_name='retestitemsw',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='EndDate'),
        ),
        migrations.AddField(
            model_name='retestitemsw',
            name='existing_device_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='已有设备ID'),
        ),
        migrations.AddField(
            model_name='retestitemsw',
            name='feature_ready_1',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Feature ready'),
        ),
        migrations.AddField(
            model_name='retestitemsw',
            name='feature_ready_2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Feature ready'),
        ),
        migrations.AddField(
            model_name='retestitemsw',
            name='feature_ready_3',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Feature ready'),
        ),
        migrations.AddField(
            model_name='retestitemsw',
            name='feature_ready_4',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Feature ready'),
        ),
        migrations.AddField(
            model_name='retestitemsw',
            name='item_1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Item'),
        ),
        migrations.AddField(
            model_name='retestitemsw',
            name='item_2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Item'),
        ),
        migrations.AddField(
            model_name='retestitemsw',
            name='item_3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Item'),
        ),
        migrations.AddField(
            model_name='retestitemsw',
            name='new_device_requirement',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='新增设备需求'),
        ),
        migrations.AddField(
            model_name='retestitemsw',
            name='sa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SA'),
        ),
        migrations.AddField(
            model_name='retestitemsw',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='StartDate'),
        ),
        migrations.AddField(
            model_name='retestitemsw',
            name='tc_category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='TC Category'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='bios',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='BIOS'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='ee',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='EE'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='EndDate'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='existing_device_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='已有设备ID'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='feature_ready_1',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Feature ready'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='feature_ready_2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Feature ready'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='feature_ready_3',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Feature ready'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='feature_ready_4',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Feature ready'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='item_1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Item'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='item_2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Item'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='item_3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Item'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='new_device_requirement',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='新增设备需求'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='sa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SA'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='StartDate'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='tc_category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='TC Category'),
        ),
        migrations.AddField(
            model_name='testplanswaio',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='EndDate'),
        ),
        migrations.AddField(
            model_name='testplanswaio',
            name='existing_device_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='已有设备ID'),
        ),
        migrations.AddField(
            model_name='testplanswaio',
            name='new_device_requirement',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='新增设备需求'),
        ),
        migrations.AddField(
            model_name='testplanswaio',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='StartDate'),
        ),
    ]
