# Generated by Django 2.1.7 on 2026-09-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlanSW', '0033_auto_20260624_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='retestitemsw',
            name='Result',
            field=models.CharField(blank=True, choices=[('', ''), ('PASS', 'PASS'), ('FAIL', 'FAIL'), ('BLOCK', 'BLOCK'), ('NS', 'NS'), ('NA', 'NA')], default='', max_length=10, null=True, verbose_name='Result'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='Result',
            field=models.CharField(blank=True, choices=[('', ''), ('PASS', 'PASS'), ('FAIL', 'FAIL'), ('BLOCK', 'BLOCK'), ('NS', 'NS'), ('NA', 'NA')], default='', max_length=10, null=True, verbose_name='Result'),
        ),
        migrations.AddField(
            model_name='testplanswaio',
            name='Result',
            field=models.CharField(blank=True, choices=[('', ''), ('PASS', 'PASS'), ('FAIL', 'FAIL'), ('BLOCK', 'BLOCK'), ('NS', 'NS'), ('NA', 'NA')], default='', max_length=10, null=True, verbose_name='Result'),
        ),
        migrations.AlterField(
            model_name='testitemsw',
            name='Phase',
            field=models.CharField(choices=[('', ''), ('A(EVT)', 'A(EVT)'), ('B(FVT)', 'B(FVT)'), ('C(SIT)', 'C(SIT)'), ('FFRT', 'FFRT'), ('Others', 'Others')], default='', max_length=20, verbose_name='Phase'),
        ),
    ]
