# Generated by Django 2.1.7 on 2026-09-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlanSW', '0034_auto_20260901_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='retestitemsw',
            name='ECR',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='ECR'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='ECR',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='ECR'),
        ),
        migrations.AddField(
            model_name='testplanswaio',
            name='ECR',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='ECR'),
        ),
    ]
