# Generated by Django 2.1.7 on 2024-08-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A31LessonLProject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a31testprojectll',
            name='Project',
            field=models.CharField(max_length=100, unique=True, verbose_name='Project'),
        ),
    ]
