# Generated by Django 2.1.7 on 2024-10-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A31LessonLProject', '0002_auto_20240828_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='A31reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.ImageField(upload_to='reports/A31/LessonProjectResult/', verbose_name='报告地址')),
                ('single', models.CharField(blank=True, max_length=200, null=True, verbose_name='报告名称')),
            ],
        ),
        migrations.AddField(
            model_name='a31lessonlearn_project',
            name='Report',
            field=models.ManyToManyField(blank=True, related_name='reports', to='A31LessonLProject.A31reports', verbose_name='报告表'),
        ),
    ]
