# Generated by Django 2.1.7 on 2024-10-08 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A31LessonLProject', '0003_auto_20241008_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='a31lessonlearn_project',
            name='Report',
        ),
        migrations.DeleteModel(
            name='A31reports',
        ),
    ]
