# Generated by Django 2.1.7 on 2025-09-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A31LessonLProject', '0004_auto_20241008_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a31lesson_learn',
            name='Category',
            field=models.CharField(choices=[('', ''), ('Reliability', 'Reliability'), ('Compatibility', 'Compatibility'), ('Common', 'Common')], default='Reliability', max_length=100),
        ),
    ]
