# Generated by Django 2.1.7 on 2025-02-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpecDownload', '0002_specdownload_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='files_SopDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='files_SopDevice/', verbose_name='文件内容')),
                ('single', models.CharField(blank=True, max_length=100, null=True, verbose_name='文件名称')),
            ],
        ),
        migrations.CreateModel(
            name='files_SopProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='files_SopProcess/', verbose_name='文件内容')),
                ('single', models.CharField(blank=True, max_length=100, null=True, verbose_name='文件名称')),
            ],
        ),
        migrations.CreateModel(
            name='files_SopRom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='files_SopRom/', verbose_name='文件内容')),
                ('single', models.CharField(blank=True, max_length=100, null=True, verbose_name='文件名称')),
            ],
        ),
        migrations.CreateModel(
            name='ManagementSopDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Num', models.CharField(max_length=10, verbose_name='No.')),
                ('Title', models.CharField(default='', max_length=200, verbose_name='Title')),
                ('Description', models.CharField(max_length=1000, verbose_name='Description')),
                ('Version', models.CharField(max_length=20, verbose_name='Version')),
                ('editor', models.CharField(max_length=100, verbose_name='editor')),
                ('edit_time', models.CharField(max_length=26, verbose_name='edit_time')),
                ('files_Spec', models.ManyToManyField(blank=True, related_name='files_SopDevice', to='SpecDownload.files_SopDevice', verbose_name='图文件表')),
            ],
        ),
        migrations.CreateModel(
            name='ManagementSopProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Num', models.CharField(max_length=10, verbose_name='No.')),
                ('Title', models.CharField(default='', max_length=200, verbose_name='Title')),
                ('Description', models.CharField(max_length=1000, verbose_name='Description')),
                ('Version', models.CharField(max_length=20, verbose_name='Version')),
                ('editor', models.CharField(max_length=100, verbose_name='editor')),
                ('edit_time', models.CharField(max_length=26, verbose_name='edit_time')),
                ('files_Spec', models.ManyToManyField(blank=True, related_name='files_SopProcess', to='SpecDownload.files_SopProcess', verbose_name='图文件表')),
            ],
        ),
        migrations.CreateModel(
            name='ManagementSopRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Num', models.CharField(max_length=10, verbose_name='No.')),
                ('Title', models.CharField(default='', max_length=200, verbose_name='Title')),
                ('Description', models.CharField(max_length=1000, verbose_name='Description')),
                ('Version', models.CharField(max_length=20, verbose_name='Version')),
                ('editor', models.CharField(max_length=100, verbose_name='editor')),
                ('edit_time', models.CharField(max_length=26, verbose_name='edit_time')),
                ('files_Spec', models.ManyToManyField(blank=True, related_name='files_SopRom', to='SpecDownload.files_SopRom', verbose_name='图文件表')),
            ],
        ),
    ]
