# Generated by Django 2.1.7 on 2024-07-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0028_auto_20240628_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_learn',
            name='video',
            field=models.ManyToManyField(blank=True, related_name='video', to='app01.Files', verbose_name='视频表'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='department',
            field=models.IntegerField(choices=[(3, 'PM'), (4, '其它部门'), (2, '开发部门'), (1, '测试部门')], default=1, verbose_name='部门'),
        ),
    ]
