# Generated by Django 2.1.7 on 2024-09-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0030_auto_20240729_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfoindct',
            name='DQAQM',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='DQAQM'),
        ),
        migrations.AddField(
            model_name='projectinfoindct',
            name='DQAQMNum',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='DQAQMNum'),
        ),
        migrations.AlterField(
            model_name='lesson_learn',
            name='video',
            field=models.ManyToManyField(blank=True, related_name='video', to='app01.Files', verbose_name='视频表'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='department',
            field=models.IntegerField(choices=[(1, '测试部门'), (2, '开发部门'), (4, '其它部门'), (3, 'PM')], default=1, verbose_name='部门'),
        ),
    ]
