# Generated by Django 2.1.7 on 2024-12-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0032_auto_20240912_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectinfoindct',
            options={'verbose_name': 'ProjectinfoinDCT', 'verbose_name_plural': 'ProjectinfoinDCT'},
        ),
        migrations.AlterField(
            model_name='lesson_learn',
            name='video',
            field=models.ManyToManyField(blank=True, related_name='video', to='app01.Files', verbose_name='视频表'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='department',
            field=models.IntegerField(choices=[(2, '开发部门'), (3, 'PM'), (1, '测试部门'), (4, '其它部门')], default=1, verbose_name='部门'),
        ),
    ]
