# Generated by Django 2.1.7 on 2025-05-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0036_auto_20250508_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_learn',
            name='video',
            field=models.ManyToManyField(blank=True, related_name='video', to='app01.Files', verbose_name='视频表'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='department',
            field=models.IntegerField(choices=[(1, '测试部门'), (4, '其它部门'), (3, 'PM'), (2, '开发部门')], default=1, verbose_name='部门'),
        ),
    ]
