# Generated by Django 2.1.7 on 2025-05-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0038_auto_20250522_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='CNname',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='Seat',
            field=models.CharField(blank=True, choices=[('KS-Plant5', 'KS-Plant5'), ('KS-Plant3', 'KS-Plant3'), ('KS-Plant2', 'KS-Plant2'), ('CQ', 'CQ'), ('CD', 'CD'), ('TPE', 'TPE'), ('PCP', 'PCP'), ('LKE', 'LKE')], max_length=108, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='Tel',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='lesson_learn',
            name='video',
            field=models.ManyToManyField(blank=True, related_name='video', to='app01.Files', verbose_name='视频表'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='department',
            field=models.IntegerField(choices=[(2, '开发部门'), (1, '测试部门'), (3, 'PM'), (4, '其它部门')], default=1, verbose_name='部门'),
        ),
    ]
