# Generated by Django 2.1.7 on 2026-02-10 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app01', '0041_auto_20260210_1523'),
        ('CQM', '0013_auto_20240624_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='UEBatch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False, verbose_name='批次ID')),
                ('batch_name', models.CharField(max_length=100, verbose_name='批次名称')),
                ('test_date', models.DateField(verbose_name='测试日期')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.UserInfo', verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='CQM.CQMProject', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'UE检查批次',
                'verbose_name_plural': 'UE检查批次',
                'ordering': ['project', '-batch_name'],
            },
        ),
        migrations.CreateModel(
            name='UEInspectionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(max_length=20, verbose_name='Item')),
                ('Function', models.CharField(choices=[('Reliability', 'Reliability'), ('Compatibility', 'Compatibility')], max_length=50, verbose_name='Function')),
                ('Category', models.CharField(max_length=100, verbose_name='Category')),
                ('characteristic', models.CharField(max_length=200, verbose_name='Characteristic')),
                ('detailed_description', models.TextField(verbose_name='詳細說明（Detailed Description）')),
                ('inspect_method', models.TextField(verbose_name='pect Methord')),
            ],
            options={
                'verbose_name': 'UE检查项目',
                'verbose_name_plural': 'UE检查项目',
                'ordering': ['Item'],
            },
        ),
        migrations.CreateModel(
            name='UEScoreRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录ID')),
                ('OneStar', models.CharField(blank=True, choices=[('V', 'V')], max_length=20, verbose_name='★')),
                ('TwoStar', models.CharField(blank=True, choices=[('V', 'V')], max_length=20, verbose_name='★★')),
                ('ThreeStar', models.CharField(blank=True, choices=[('V', 'V')], max_length=20, verbose_name='★★★')),
                ('NotSup', models.CharField(blank=True, choices=[('N/S', 'N/S')], max_length=20, verbose_name='Not Support')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('scored_date', models.DateTimeField(auto_now_add=True, verbose_name='评分时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_records', to='UElist.UEBatch', verbose_name='所属批次')),
                ('inspection_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UElist.UEInspectionItem', verbose_name='检查项目')),
                ('scorer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.UserInfo', verbose_name='评分人')),
            ],
            options={
                'verbose_name': 'UE评分记录',
                'verbose_name_plural': 'UE评分记录',
                'ordering': ['batch', 'inspection_item__item_id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='uebatch',
            unique_together={('project', 'batch_name')},
        ),
    ]
