# Generated by Django 2.1.7 on 2026-02-13 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0042_auto_20260213_1418'),
        ('UElist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uebatch',
            name='tester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uebatch_tested', to='app01.UserInfo', verbose_name='测试人'),
        ),
        migrations.AlterField(
            model_name='uebatch',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uebatch_created', to='app01.UserInfo', verbose_name='创建人'),
        ),
    ]
