# Generated by Django 2.1.7 on 2026-02-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0043_auto_20260213_1514'),
        ('UElist', '0002_auto_20260213_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uebatch',
            name='tester',
        ),
        migrations.AddField(
            model_name='uebatch',
            name='tester',
            field=models.ManyToManyField(related_name='ue_batches', to='app01.UserInfo', verbose_name='测试人员'),
        ),
    ]
