# Generated by Django 2.1.7 on 2026-02-13 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UElist', '0003_auto_20260213_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uebatch',
            old_name='tester',
            new_name='testers',
        ),
    ]
