# Generated by Django 2.1.7 on 2026-02-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UElist', '0004_auto_20260213_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='ueinspectionitem',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10, verbose_name='状态'),
        ),
    ]
