# Generated by Django 2.1.7 on 2025-03-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.CharField(max_length=100, verbose_name='年份')),
                ('Ledger', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='會計科目')),
                ('Jan', models.FloatField(blank=True, max_length=50, null=True, verbose_name='Jan')),
                ('Feb', models.FloatField(blank=True, max_length=50, null=True, verbose_name='Feb')),
                ('Mar', models.FloatField(blank=True, max_length=50, null=True, verbose_name='Mar')),
                ('Apr', models.FloatField(blank=True, max_length=50, null=True, verbose_name='Apr')),
                ('May', models.FloatField(blank=True, max_length=50, null=True, verbose_name='May')),
                ('Jun', models.FloatField(blank=True, max_length=50, null=True, verbose_name='Jun')),
                ('Jul', models.FloatField(blank=True, max_length=50, null=True, verbose_name='Jul')),
                ('Aug', models.FloatField(blank=True, max_length=50, null=True, verbose_name='Aug')),
                ('Sep', models.FloatField(blank=True, max_length=50, null=True, verbose_name='Sep')),
                ('Oct', models.FloatField(blank=True, max_length=50, null=True, verbose_name='Oct')),
                ('Nov', models.FloatField(blank=True, max_length=50, null=True, verbose_name='Nov')),
                ('Dec', models.FloatField(blank=True, max_length=50, null=True, verbose_name='Dec')),
            ],
            options={
                'verbose_name': '預算費用',
                'verbose_name_plural': '預算費用',
            },
        ),
        migrations.CreateModel(
            name='ReceiptAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.CharField(max_length=100, verbose_name='年份')),
                ('Ledger', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='會計科目')),
                ('Jan', models.FloatField(blank=True, max_length=50, null=True, verbose_name='Jan')),
                ('Feb', models.FloatField(blank=True, max_length=50, null=True, verbose_name='Feb')),
                ('Mar', models.FloatField(blank=True, max_length=50, null=True, verbose_name='Mar')),
                ('Apr', models.FloatField(blank=True, max_length=50, null=True, verbose_name='Apr')),
                ('May', models.FloatField(blank=True, max_length=50, null=True, verbose_name='May')),
                ('Jun', models.FloatField(blank=True, max_length=50, null=True, verbose_name='Jun')),
                ('Jul', models.FloatField(blank=True, max_length=50, null=True, verbose_name='Jul')),
                ('Aug', models.FloatField(blank=True, max_length=50, null=True, verbose_name='Aug')),
                ('Sep', models.FloatField(blank=True, max_length=50, null=True, verbose_name='Sep')),
                ('Oct', models.FloatField(blank=True, max_length=50, null=True, verbose_name='Oct')),
                ('Nov', models.FloatField(blank=True, max_length=50, null=True, verbose_name='Nov')),
                ('Dec', models.FloatField(blank=True, max_length=50, null=True, verbose_name='Dec')),
            ],
            options={
                'verbose_name': '實際入賬金額',
                'verbose_name_plural': '實際入賬金額',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.CharField(default='', max_length=12, verbose_name='Year')),
                ('Ledger', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='會計科目')),
                ('Name', models.CharField(blank=True, max_length=500, null=True, verbose_name='設備名稱/项目')),
                ('Status', models.CharField(blank=True, max_length=50, null=True, verbose_name='到貨狀態')),
                ('ModelSpecifications', models.CharField(blank=True, max_length=1000, null=True, verbose_name='型號規格')),
                ('SubscribeDate', models.DateField(blank=True, null=True, verbose_name='申購日期')),
                ('SubscribeForm', models.CharField(blank=True, max_length=50, null=True, verbose_name='申購單')),
                ('SubscribeUnitPrice', models.FloatField(blank=True, max_length=20, null=True, verbose_name='申購單價')),
                ('Number', models.IntegerField(blank=True, null=True, verbose_name='數量')),
                ('AcceptanceForm', models.CharField(blank=True, max_length=20, null=True, verbose_name='驗收單號')),
                ('AcceptanceDate', models.DateField(blank=True, null=True, verbose_name='驗收日期')),
                ('ActUnitPrice', models.FloatField(blank=True, max_length=20, null=True, verbose_name='實際單價')),
                ('Customer', models.CharField(blank=True, max_length=20, null=True, verbose_name='客戶別')),
                ('ProjectCode', models.CharField(blank=True, max_length=50, null=True, verbose_name='Project Code')),
                ('Department', models.CharField(blank=True, max_length=20, null=True, verbose_name='申購部門')),
                ('RequisitionerNum', models.CharField(blank=True, max_length=20, null=True, verbose_name='申購人工號')),
                ('Requisitioner', models.CharField(blank=True, max_length=20, null=True, verbose_name='申購人')),
            ],
            options={
                'verbose_name': 'SubscriptionStatus',
                'verbose_name_plural': 'SubscriptionStatus',
            },
        ),
    ]
