# Generated by Django 2.1.7 on 2024-09-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app01', '0032_auto_20240912_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriticalIssue',
            fields=[
                ('IssueNum', models.AutoField(default=100001, primary_key=True, serialize=False)),
                ('CG', models.CharField(choices=[('', ''), ('C38(NB)', 'C38(NB)'), ('C38(NB)-SMB', 'C38(NB)-SMB'), ('C38(AIO)', 'C38(AIO)'), ('T88(AIO)', 'T88(AIO)'), ('T89(NB)', 'T89(NB)'), ('A39', 'A39'), ('C85', 'C85'), ('A31', 'A31'), ('A32', 'A32'), ('Others', 'Others')], max_length=20, verbose_name='Customer')),
                ('Category', models.CharField(choices=[('', ''), ('shutdown', 'shutdown'), ('burnt out', 'burnt out'), ('blue screen', 'blue screen'), ('restart', 'restart'), ('black screen', 'black screen'), ('data lost', 'data lost')], default='Reliability', max_length=100)),
                ('Object', models.CharField(max_length=100)),
                ('Symptom', models.CharField(max_length=1000)),
                ('Reproduce_Steps', models.CharField(blank=True, default='', max_length=2000, verbose_name='Reproduce_Steps')),
                ('Root_Cause', models.CharField(max_length=2000, verbose_name='Root_Cause')),
                ('Solution', models.CharField(max_length=2000, verbose_name='Solution')),
                ('Action', models.CharField(blank=True, default='', max_length=2000, verbose_name='Action')),
                ('Project', models.CharField(blank=True, default='', max_length=200, verbose_name='Project')),
                ('Status', models.CharField(blank=True, choices=[('', ''), ('active', 'active'), ('inactive', 'inactive')], default='active', max_length=20, verbose_name='Status')),
                ('editor', models.CharField(max_length=100)),
                ('edit_time', models.CharField(blank=True, max_length=26, verbose_name='edit_time')),
            ],
            options={
                'verbose_name': 'CriticalIssue',
                'verbose_name_plural': 'CriticalIssue',
            },
        ),
        migrations.CreateModel(
            name='CriticalIssueCrossResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('', ''), ('Pass', 'Pass'), ('Fail', 'Fail'), ('N/S', 'N/S'), ('N/A', 'N/A'), ('N/P', 'N/P')], max_length=20)),
                ('Comment', models.CharField(max_length=1000)),
                ('editor', models.CharField(default='', max_length=100)),
                ('edit_time', models.CharField(blank=True, default='', max_length=26, verbose_name='edit_time')),
                ('CriticalIssue', models.ForeignKey(on_delete=True, to='CriticalIssueCrossCheck.CriticalIssue')),
            ],
        ),
        migrations.CreateModel(
            name='CriticalIssuefiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='videos/CriticalIssue/', verbose_name='视频内容')),
                ('single', models.CharField(blank=True, max_length=200, null=True, verbose_name='视频名称')),
            ],
        ),
        migrations.CreateModel(
            name='CriticalIssueImgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img/CriticalIssue/', verbose_name='图片地址')),
                ('single', models.CharField(blank=True, max_length=200, null=True, verbose_name='图片名称')),
            ],
        ),
        migrations.CreateModel(
            name='CriticalIssueTestProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer', models.CharField(choices=[('', ''), ('C38(NB)', 'C38(NB)'), ('C38(NB)-SMB', 'C38(NB)-SMB'), ('C38(AIO)', 'C38(AIO)'), ('T88(AIO)', 'T88(AIO)'), ('T89(NB)', 'T89(NB)'), ('A39', 'A39'), ('C85', 'C85'), ('A31', 'A31'), ('A32', 'A32'), ('Others', 'Others')], max_length=20, verbose_name='Customer')),
                ('Project', models.CharField(max_length=100, unique=True, verbose_name='Project')),
                ('Owner', models.ManyToManyField(to='app01.UserInfo')),
            ],
            options={
                'verbose_name': 'CriticalIssueTestProject',
                'verbose_name_plural': 'CriticalIssueTestProject',
            },
        ),
        migrations.AddField(
            model_name='criticalissuecrossresult',
            name='Projectinfo',
            field=models.ForeignKey(on_delete=True, to='CriticalIssueCrossCheck.CriticalIssueTestProject'),
        ),
        migrations.AddField(
            model_name='criticalissue',
            name='Photo',
            field=models.ManyToManyField(blank=True, related_name='imgs', to='CriticalIssueCrossCheck.CriticalIssueImgs', verbose_name='图片表'),
        ),
        migrations.AddField(
            model_name='criticalissue',
            name='video',
            field=models.ManyToManyField(blank=True, related_name='video', to='CriticalIssueCrossCheck.CriticalIssuefiles', verbose_name='视频表'),
        ),
    ]
