# Generated by Django 2.1.7 on 2024-12-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CriticalIssueCrossCheck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criticalissue',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
