# Generated by Django 2.1.7 on 2025-08-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapitalExpenditure', '0005_c38customert88aiodepartmentcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitalexpenditure',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='capitalexpenditure',
            name='creator',
            field=models.CharField(default='', max_length=20, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='capitalexpenditure',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
