# Generated by Django 2.1.7 on 2026-05-27 13:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app01', '0044_auto_20260527_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcr_no', models.CharField(max_length=50, verbose_name='PCR No')),
                ('pcr_title', models.CharField(max_length=200, verbose_name='PCR Title')),
                ('Customer', models.CharField(choices=[('NB', 'NB'), ('AIO', 'AIO')], max_length=10, verbose_name='Customer')),
                ('Project', models.CharField(max_length=50, verbose_name='Project')),
                ('Compalproject', models.CharField(max_length=50, verbose_name='Compal Project')),
                ('phase', models.CharField(choices=[('NPI', 'NPI'), ('INV', 'INV')], max_length=3, verbose_name='NPI or INV')),
                ('category', models.CharField(max_length=50, verbose_name='Category')),
                ('receive_date', models.DateField(verbose_name='Receive Date')),
                ('status', models.CharField(choices=[('Perform', 'Perform'), ('On going', 'On going'), ('Plan', 'Plan'), ('Ongoing', 'Ongoing')], max_length=10, verbose_name='Status')),
                ('sample_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Sample Q'ty")),
                ('hc_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name="HC Q'ty")),
                ('hc_days', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='HC Days')),
                ('pd', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, verbose_name='PD')),
                ('device_fee_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Device fee (USD)')),
                ('dqa_nre_mail_to_pm', models.TextField(blank=True, verbose_name='DQA NRE mail to PM')),
                ('pm_send_nre_to_sales', models.BooleanField(default=False, verbose_name='PM send NRE to Sales')),
                ('execution_start', models.DateField(blank=True, null=True, verbose_name='Execution Start')),
                ('execution_end', models.DateField(blank=True, null=True, verbose_name='Execution End')),
                ('whether_in_budget', models.BooleanField(default=True, verbose_name='Whether In Budget')),
                ('in_budget_but_cost_add', models.BooleanField(default=False, verbose_name='In budget but cost add')),
                ('remark', models.TextField(blank=True, verbose_name='Remark')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='pcr_attachments/%Y/%m/', verbose_name='報NRE郵件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.UserInfo', verbose_name='创建者')),
            ],
            options={
                'verbose_name': 'PCR',
                'verbose_name_plural': 'PCR',
                'ordering': ['-receive_date'],
            },
        ),
        migrations.AddIndex(
            model_name='pcr',
            index=models.Index(fields=['Project', 'phase', 'status'], name='PCRList_pcr_Project_0db1c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pcr',
            unique_together={('pcr_no', 'Project', 'pcr_title')},
        ),
    ]
