# Generated by Django 2.1.7 on 2026-05-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCRList', '0002_auto_20260527_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcr',
            name='pcr_no',
            field=models.CharField(max_length=100, verbose_name='PCR No'),
        ),
        migrations.AlterField(
            model_name='pcr',
            name='receive_date',
            field=models.DateField(null=True, verbose_name='Receive Date'),
        ),
    ]
