# Generated by Django 2.1.7 on 2026-08-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCRList', '0003_auto_20260527_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcr',
            name='Customer',
            field=models.CharField(choices=[('C38(NB)', 'C38(NB)'), ('C38(AIO)', 'C38(AIO)'), ('A08(NB)', 'A08(NB)'), ('T89(NB)', 'T89(NB)'), ('T88(AIO)', 'T88(AIO)')], max_length=10, verbose_name='Customer'),
        ),
    ]
