# Generated by Django 2.1.7 on 2026-08-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCRList', '0004_auto_20260812_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcr',
            name='year',
            field=models.CharField(blank=True, max_length=10, verbose_name='Year'),
        ),
    ]
