# Generated by Django 2.1.7 on 2026-08-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCRList', '0005_pcr_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcr',
            name='Project',
            field=models.CharField(blank=True, max_length=500, verbose_name='Project'),
        ),
    ]
