# Generated by Django 2.1.7 on 2025-09-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlanSWOS', '0007_auto_20250903_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testplansw',
            name='Remark',
            field=models.CharField(blank=True, default='', max_length=3500, null=True, verbose_name='Remark'),
        ),
    ]
