# Generated by Django 2.1.7 on 2026-04-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlanSWOS', '0009_auto_20251117_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testplansw',
            name='Phase',
            field=models.CharField(choices=[('', ''), ('B(FVT)', 'B(FVT)'), ('FVT Regression1', 'FVT Regression1'), ('FVT Regression2', 'FVT Regression2'), ('FVT Regression3', 'FVT Regression3'), ('FVT Regression4', 'FVT Regression4'), ('FVT Regression5', 'FVT Regression5'), ('C(SIT)', 'C(SIT)'), ('SIT2', 'SIT2'), ('SIT Regression1', 'SIT Regression1'), ('SIT Regression2', 'SIT Regression2'), ('SIT Regression3', 'SIT Regression3'), ('SIT Regression4', 'SIT Regression4'), ('SIT Regression5', 'SIT Regression5'), ('GSKU', 'GSKU'), ('Downgrade', 'Downgrade'), ('Wave', 'Wave'), ('Wave2', 'Wave2'), ('Wave3', 'Wave3'), ('Wave4', 'Wave4'), ('Wave5', 'Wave5'), ('OOC', 'OOC'), ('OOC2', 'OOC2'), ('OOC3', 'OOC3'), ('OOC4', 'OOC4'), ('OOC5', 'OOC5'), ('OOC6', 'OOC6'), ('FFRT', 'FFRT'), ('FFRT2', 'FFRT2'), ('FFRT3', 'FFRT3'), ('FFRT4', 'FFRT4'), ('FFRT5', 'FFRT5'), ('FFRT6', 'FFRT6'), ('SIT_U9', 'SIT_U9'), ('U9_FFRT', 'U9_FFRT'), ('U9_FFRT2', 'U9_FFRT2'), ('U9_FFRT3', 'U9_FFRT3'), ('GSKU_FFRT', 'GSKU_FFRT'), ('GSKU_FFRT2', 'GSKU_FFRT2'), ('GSKU_FFRT3', 'GSKU_FFRT3'), ('DG_FFRT', 'DG_FFRT'), ('DG_FFRT2', 'DG_FFRT2'), ('DG_FFRT3', 'DG_FFRT3'), ('Others', 'Others')], default='', max_length=20, verbose_name='Phase'),
        ),
        migrations.AlterField(
            model_name='testplanswaio',
            name='Phase',
            field=models.CharField(choices=[('', ''), ('B(SDV)', 'B(SDV)'), ('FVT Regression1', 'FVT Regression1'), ('FVT Regression2', 'FVT Regression2'), ('FVT Regression3', 'FVT Regression3'), ('FVT Regression4', 'FVT Regression4'), ('FVT Regression5', 'FVT Regression5'), ('C(SIT)', 'C(SIT)'), ('SIT Regression1', 'SIT Regression1'), ('SIT Regression2', 'SIT Regression2'), ('SIT Regression3', 'SIT Regression3'), ('SIT Regression4', 'SIT Regression4'), ('SIT Regression5', 'SIT Regression5'), ('Wave2', 'Wave2'), ('Wave3', 'Wave3'), ('EELP+', 'EELP+'), ('OOC', 'OOC'), ('OOC2', 'OOC2'), ('OOC3', 'OOC3'), ('Others', 'Others')], default='', max_length=20, verbose_name='Phase'),
        ),
        migrations.AlterField(
            model_name='testprojectsw',
            name='Phase',
            field=models.CharField(choices=[('', ''), ('B(FVT)', 'B(FVT)'), ('FVT Regression1', 'FVT Regression1'), ('FVT Regression2', 'FVT Regression2'), ('FVT Regression3', 'FVT Regression3'), ('FVT Regression4', 'FVT Regression4'), ('FVT Regression5', 'FVT Regression5'), ('C(SIT)', 'C(SIT)'), ('SIT2', 'SIT2'), ('SIT Regression1', 'SIT Regression1'), ('SIT Regression2', 'SIT Regression2'), ('SIT Regression3', 'SIT Regression3'), ('SIT Regression4', 'SIT Regression4'), ('SIT Regression5', 'SIT Regression5'), ('GSKU', 'GSKU'), ('Downgrade', 'Downgrade'), ('Wave', 'Wave'), ('Wave2', 'Wave2'), ('Wave3', 'Wave3'), ('Wave4', 'Wave4'), ('Wave5', 'Wave5'), ('OOC', 'OOC'), ('OOC2', 'OOC2'), ('OOC3', 'OOC3'), ('OOC4', 'OOC4'), ('OOC5', 'OOC5'), ('OOC6', 'OOC6'), ('FFRT', 'FFRT'), ('FFRT2', 'FFRT2'), ('FFRT3', 'FFRT3'), ('FFRT4', 'FFRT4'), ('FFRT5', 'FFRT5'), ('FFRT6', 'FFRT6'), ('SIT_U9', 'SIT_U9'), ('U9_FFRT', 'U9_FFRT'), ('U9_FFRT2', 'U9_FFRT2'), ('U9_FFRT3', 'U9_FFRT3'), ('GSKU_FFRT', 'GSKU_FFRT'), ('GSKU_FFRT2', 'GSKU_FFRT2'), ('GSKU_FFRT3', 'GSKU_FFRT3'), ('DG_FFRT', 'DG_FFRT'), ('DG_FFRT2', 'DG_FFRT2'), ('DG_FFRT3', 'DG_FFRT3'), ('Others', 'Others')], max_length=20, verbose_name='Phase'),
        ),
        migrations.AlterField(
            model_name='testprojectswaio',
            name='Phase',
            field=models.CharField(choices=[('', ''), ('B(SDV)', 'B(SDV)'), ('FVT Regression1', 'FVT Regression1'), ('FVT Regression2', 'FVT Regression2'), ('FVT Regression3', 'FVT Regression3'), ('FVT Regression4', 'FVT Regression4'), ('FVT Regression5', 'FVT Regression5'), ('C(SIT)', 'C(SIT)'), ('SIT Regression1', 'SIT Regression1'), ('SIT Regression2', 'SIT Regression2'), ('SIT Regression3', 'SIT Regression3'), ('SIT Regression4', 'SIT Regression4'), ('SIT Regression5', 'SIT Regression5'), ('Wave2', 'Wave2'), ('Wave3', 'Wave3'), ('EELP+', 'EELP+'), ('OOC', 'OOC'), ('OOC2', 'OOC2'), ('OOC3', 'OOC3'), ('Others', 'Others')], max_length=20, verbose_name='Phase'),
        ),
    ]
