# Generated by Django 2.1.7 on 2026-06-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlanSWOS', '0012_auto_20260625_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='testplanswaio',
            name='BaseTimeWeight',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='Base Time*Weight'),
        ),
        migrations.AddField(
            model_name='testplanswaio',
            name='Case_ID',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Case ID'),
        ),
        migrations.AddField(
            model_name='testplanswaio',
            name='Weight',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='Weight'),
        ),
    ]
