# Generated by Django 2.1.7 on 2025-07-09 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='大类名称')),
            ],
        ),
        migrations.CreateModel(
            name='CommonFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CG', models.CharField(choices=[('', ''), ('C38NB', 'C38NB'), ('C38AIO', 'C38AIO'), ('T88AIO', 'T88AIO'), ('T89', 'T89'), ('Common', 'Common')], default='', max_length=10)),
                ('SWHW', models.CharField(choices=[('', ''), ('SW', 'SW'), ('HW', 'HW'), ('Common', 'Common')], default='', max_length=10)),
                ('Item', models.CharField(max_length=100, verbose_name='Item')),
                ('Description', models.CharField(max_length=1000, verbose_name='Description')),
                ('Version', models.CharField(max_length=20, verbose_name='Version')),
                ('Owner', models.CharField(max_length=50, verbose_name='Owner')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '知行智库',
                'verbose_name_plural': '知行智库',
            },
        ),
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='CommonFiles/', verbose_name='文件内容')),
                ('single', models.CharField(blank=True, max_length=100, null=True, verbose_name='文件名称')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='细项名称')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='CommonFiles.Category')),
            ],
        ),
        migrations.AddField(
            model_name='commonfiles',
            name='Attachment',
            field=models.ManyToManyField(blank=True, related_name='Attachment', to='CommonFiles.files', verbose_name='文件表'),
        ),
        migrations.AddField(
            model_name='commonfiles',
            name='Category_L1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommonFiles.Category', verbose_name='大类'),
        ),
        migrations.AddField(
            model_name='commonfiles',
            name='Category_L2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommonFiles.SubCategory', verbose_name='细项'),
        ),
    ]
