# Generated by Django 2.1.7 on 2025-07-11 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CommonFiles', '0002_auto_20250711_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonfiles',
            name='Category_L2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CommonFiles.SubCategory', verbose_name='细项'),
        ),
        migrations.AlterField(
            model_name='commonfiles',
            name='SWHW',
            field=models.CharField(blank=True, choices=[('', ''), ('SW', 'SW'), ('HW', 'HW'), ('Common', 'Common')], default='', max_length=10, null=True),
        ),
    ]
