# Generated by Django 2.1.7 on 2025-09-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommonFiles', '0003_auto_20250711_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='file_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='文件类型'),
        ),
    ]
