# Generated by Django 2.1.7 on 2025-09-16 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CommonFiles', '0004_files_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='file_type',
        ),
    ]
