# Generated by Django 2.1.7 on 2025-03-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MQM', '0007_auto_20230131_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mqm',
            name='Customer',
            field=models.CharField(choices=[('', ''), ('C38(NB)', 'C38(NB)'), ('C38(AIO)', 'C38(AIO)'), ('T88(AIO)', 'T88(AIO)'), ('T89(NB)', 'T89(NB)'), ('A39', 'A39'), ('C85', 'C85'), ('Others', 'Others')], default='', max_length=10, verbose_name='Customer'),
        ),
    ]
