# Generated by Django 2.1.7 on 2025-10-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnowIssue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowissue_m',
            name='Issue_Title',
            field=models.CharField(max_length=2000, verbose_name='Issue_Title'),
        ),
        migrations.AlterField(
            model_name='knowissue_m',
            name='Root_Cause',
            field=models.CharField(max_length=4000, verbose_name='Root_Cause'),
        ),
    ]
