# Generated by Django 2.1.7 on 2025-05-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=50, verbose_name='大项')),
                ('Product_Type', models.CharField(max_length=50, verbose_name='细项')),
                ('Name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('Num', models.CharField(blank=True, max_length=50, null=True, verbose_name='號碼')),
                ('Manufacturer', models.CharField(blank=True, max_length=50, null=True, verbose_name='廠商')),
                ('Cost', models.FloatField(blank=True, max_length=50, null=True, verbose_name='費用(CNY)')),
                ('Account', models.CharField(blank=True, max_length=50, null=True, verbose_name='Account')),
                ('PW', models.CharField(blank=True, max_length=50, null=True, verbose_name='密碼')),
                ('Purchasing_Date', models.DateField(max_length=50, verbose_name='購買日期')),
                ('Department', models.CharField(max_length=50, verbose_name='部別')),
                ('Location', models.CharField(blank=True, max_length=50, null=True, verbose_name='位置')),
                ('Asset_Num', models.CharField(blank=True, max_length=50, null=True, verbose_name='資產編號')),
                ('Owner_Num', models.CharField(max_length=50, verbose_name='负责人工號')),
                ('Owner', models.CharField(max_length=50, verbose_name='负责人')),
                ('Mail', models.EmailField(max_length=254, verbose_name='郵件地址')),
                ('Contact_info', models.CharField(max_length=50, verbose_name='聯係方式')),
                ('Comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
                ('Editor', models.CharField(max_length=50, verbose_name='Editor')),
                ('Edit_data', models.DateTimeField(max_length=50, verbose_name='Creator_data')),
            ],
            options={
                'verbose_name': '公共设备',
                'verbose_name_plural': '公共设备',
            },
        ),
    ]
