# Generated by Django 2.1.7 on 2025-05-22 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app01', '0038_auto_20250522_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='大类名称')),
            ],
        ),
        migrations.CreateModel(
            name='CommonDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('Num', models.CharField(blank=True, max_length=50, null=True, verbose_name='號碼')),
                ('Manufacturer', models.CharField(blank=True, max_length=50, null=True, verbose_name='廠商')),
                ('Cost', models.FloatField(blank=True, max_length=50, null=True, verbose_name='費用(CNY)')),
                ('Account', models.CharField(blank=True, max_length=50, null=True, verbose_name='Account')),
                ('PW', models.CharField(blank=True, max_length=50, null=True, verbose_name='密碼')),
                ('Purchasing_Date', models.DateField(max_length=50, verbose_name='購買日期')),
                ('Department', models.CharField(max_length=50, verbose_name='部別')),
                ('Location', models.CharField(blank=True, max_length=50, null=True, verbose_name='位置')),
                ('Asset_Num', models.CharField(blank=True, max_length=50, null=True, verbose_name='資產編號')),
                ('Dev_Status', models.CharField(blank=True, choices=[('', ''), ('使用中', '使用中'), ('損壞', '損壞'), ('閑置', '閑置'), ('報廢', '報廢')], max_length=50, null=True, verbose_name='狀態')),
                ('Mail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='郵件地址')),
                ('Contact_info', models.CharField(blank=True, max_length=50, null=True, verbose_name='聯係方式')),
                ('Comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
                ('Creator', models.CharField(max_length=50, verbose_name='Creator')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommonDevice.Category', verbose_name='大类')),
                ('Owner', models.ManyToManyField(to='app01.UserInfo')),
            ],
            options={
                'verbose_name': '公共设备',
                'verbose_name_plural': '公共设备',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='细项名称')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='CommonDevice.Category')),
            ],
        ),
        migrations.AddField(
            model_name='commondevice',
            name='Product_Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommonDevice.SubCategory', verbose_name='细项'),
        ),
    ]
