# Generated by Django 2.1.7 on 2025-07-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommonDevice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commondevice',
            name='Purpose',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='用途'),
        ),
    ]
