# Generated by Django 2.1.7 on 2025-05-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommonDevice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commondevice',
            name='Edit_data',
        ),
        migrations.AddField(
            model_name='commondevice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='commondevice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
