# Generated by Django 2.1.7 on 2025-05-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommonDevice', '0002_auto_20250506_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='commondevice',
            name='password_hash',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
