# Generated by Django 2.1.7 on 2025-05-07 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CommonDevice', '0003_commondevice_password_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commondevice',
            name='password_hash',
        ),
    ]
