# Generated by Django 2.1.7 on 2025-05-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0036_auto_20250508_1130'),
        ('CommonDevice', '0004_remove_commondevice_password_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commondevice',
            name='Contact_info',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='聯係方式'),
        ),
        migrations.AlterField(
            model_name='commondevice',
            name='Mail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='郵件地址'),
        ),
        migrations.AlterField(
            model_name='commondevice',
            name='Owner',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='负责人'),
        ),
        migrations.RemoveField(
            model_name='commondevice',
            name='Owner_Num',
        ),
        migrations.AddField(
            model_name='commondevice',
            name='Owner_Num',
            field=models.ManyToManyField(to='app01.UserInfo'),
        ),
    ]
