# Generated by Django 2.1.7 on 2025-05-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0037_auto_20250509_0939'),
        ('CommonDevice', '0005_auto_20250508_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commondevice',
            old_name='Editor',
            new_name='Creator',
        ),
        migrations.RemoveField(
            model_name='commondevice',
            name='Owner_Num',
        ),
        migrations.RemoveField(
            model_name='commondevice',
            name='Owner',
        ),
        migrations.AddField(
            model_name='commondevice',
            name='Owner',
            field=models.ManyToManyField(to='app01.UserInfo'),
        ),
    ]
