# Generated by Django 2.1.7 on 2025-05-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommonDevice', '0006_auto_20250509_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commondevice',
            name='Creator',
            field=models.CharField(max_length=50, verbose_name='Creator'),
        ),
    ]
