# Generated by Django 2.1.7 on 2024-09-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoResult', '0003_auto_20240911_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoitems',
            name='Customer',
            field=models.CharField(choices=[('', ''), ('C38(NB)', 'C38(NB)'), ('C38(AIO)', 'C38(AIO)'), ('T88(AIO)', 'T88(AIO)'), ('C85', 'C85'), ('A39', 'A39'), ('T89(NB)', 'T89(NB)'), ('Common', 'Common'), ('網絡', '網絡')], max_length=64, verbose_name='CG'),
        ),
        migrations.AlterField(
            model_name='autoproject',
            name='Customer',
            field=models.CharField(choices=[('', ''), ('C38(NB)', 'C38(NB)'), ('C38(NB)-SMB', 'C38(NB)-SMB'), ('C38(AIO)', 'C38(AIO)'), ('T88(AIO)', 'T88(AIO)'), ('A39', 'A39'), ('T89(NB)', 'T89(NB)'), ('C85', 'C85'), ('Others', 'Others')], max_length=20, verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='autoresult',
            name='Customer',
            field=models.CharField(choices=[('', ''), ('C38(NB)', 'C38(NB)'), ('C38(AIO)', 'C38(AIO)'), ('T88(AIO)', 'T88(AIO)'), ('C85', 'C85'), ('A39', 'A39'), ('T89(NB)', 'T89(NB)'), ('Common', 'Common'), ('網絡', '網絡')], max_length=64, verbose_name='CG'),
        ),
    ]
