# Generated by Django 2.1.7 on 2025-10-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoResult', '0004_auto_20240911_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='Autotool/', verbose_name='文件内容')),
                ('single', models.CharField(blank=True, max_length=100, null=True, verbose_name='文件名称')),
            ],
        ),
        migrations.AddField(
            model_name='autoitems',
            name='Import_Date',
            field=models.DateField(blank=True, max_length=50, null=True, verbose_name='導入日期'),
        ),
        migrations.AddField(
            model_name='autoitems',
            name='Ver',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='工具版本'),
        ),
        migrations.AddField(
            model_name='autoitems',
            name='proposer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='提案者'),
        ),
        migrations.AddField(
            model_name='autoresult',
            name='Import_Date',
            field=models.DateField(blank=True, max_length=50, null=True, verbose_name='導入日期'),
        ),
        migrations.AddField(
            model_name='autoresult',
            name='Ver',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='工具版本'),
        ),
        migrations.AddField(
            model_name='autoresult',
            name='proposer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='提案者'),
        ),
        migrations.AlterField(
            model_name='autoitems',
            name='Owner',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='開發者'),
        ),
        migrations.AlterField(
            model_name='autoresult',
            name='Owner',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='開發者'),
        ),
        migrations.AddField(
            model_name='autoitems',
            name='Attachment',
            field=models.ManyToManyField(blank=True, related_name='Attachment', to='AutoResult.files', verbose_name='工具及Sop'),
        ),
    ]
