# Generated by Django 2.1.7 on 2026-04-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoResult', '0006_auto_20260407_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoitems',
            name='SingleBenefit',
            field=models.FloatField(blank=True, null=True, verbose_name='單臺效益(min)'),
        ),
        migrations.AlterField(
            model_name='autoitems',
            name='BaseIncome',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Base效益(h)'),
        ),
    ]
