# Generated by Django 2.1.7 on 2026-08-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoResult', '0007_auto_20260416_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoitems',
            name='TrainingStaff',
            field=models.ManyToManyField(blank=True, related_name='training_items', to='AutoResult.PICS', verbose_name='培训人员名单'),
        ),
    ]
