# Generated by Django 2.1.7 on 2026-08-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoResult', '0008_autoitems_trainingstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pics',
            name='pic',
            field=models.ImageField(upload_to='Auto/PIC/', verbose_name='图片地址'),
        ),
    ]
