# Generated by Django 2.1.7 on 2026-05-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CQM', '0013_auto_20240624_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cqm',
            name='Customer',
            field=models.CharField(choices=[('', ''), ('C38(NB)', 'C38(NB)'), ('C38(NB)-SMB', 'C38(NB)-SMB'), ('C38(AIO)', 'C38(AIO)'), ('T88(AIO)', 'T88(AIO)'), ('A08(NB)', 'A08(NB)'), ('A39', 'A39'), ('C85', 'C85'), ('Others', 'Others')], max_length=100, verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='cqmproject',
            name='Customer',
            field=models.CharField(choices=[('', ''), ('C38(NB)', 'C38(NB)'), ('C38(NB)-SMB', 'C38(NB)-SMB'), ('C38(AIO)', 'C38(AIO)'), ('T88(AIO)', 'T88(AIO)'), ('T89(NB)', 'T89(NB)'), ('A08(NB)', 'A08(NB)'), ('A39', 'A39'), ('C85', 'C85'), ('Others', 'Others')], max_length=20, verbose_name='Customer'),
        ),
    ]
