# Generated by Django 2.1.7 on 2026-06-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='version',
            field=models.IntegerField(default=0, verbose_name='乐观锁版本号'),
        ),
    ]
