# Generated by Django 2.1.7 on 2026-06-22 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0045_auto_20260622_1430'),
        ('sales', '0003_auto_20260622_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLogistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logistics_company', models.CharField(max_length=50, verbose_name='物流公司')),
                ('logistics_no', models.CharField(max_length=50, verbose_name='物流单号')),
                ('status', models.CharField(max_length=50, verbose_name='状态')),
                ('content', models.TextField(verbose_name='物流信息内容')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='位置')),
                ('operator', models.CharField(blank=True, max_length=50, verbose_name='操作人')),
                ('track_time', models.DateTimeField(verbose_name='追踪时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '物流追踪',
                'verbose_name_plural': '物流追踪',
                'ordering': ['-track_time'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/%Y/%m/%d/', verbose_name='图片')),
                ('is_cover', models.BooleanField(default=False, verbose_name='是否封面')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='图片描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '产品图片',
                'verbose_name_plural': '产品图片',
                'ordering': ['-is_cover', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1星-非常差'), (2, '2星-差'), (3, '3星-一般'), (4, '4星-好'), (5, '5星-非常好')], verbose_name='评分')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='评价标题')),
                ('content', models.TextField(verbose_name='评价内容')),
                ('advantages', models.TextField(blank=True, verbose_name='优点')),
                ('disadvantages', models.TextField(blank=True, verbose_name='缺点')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='是否匿名')),
                ('is_approved', models.BooleanField(default=False, verbose_name='是否审核通过')),
                ('is_recommend', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '用户评价',
                'verbose_name_plural': '用户评价',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductWarehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0, verbose_name='仓库库存')),
                ('reserved_stock', models.IntegerField(default=0, verbose_name='预留库存')),
                ('min_stock', models.IntegerField(default=0, verbose_name='最低库存预警')),
                ('max_stock', models.IntegerField(default=0, verbose_name='最高库存预警')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '产品仓库库存',
                'verbose_name_plural': '产品仓库库存',
            },
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='review_images/%Y/%m/%d/', verbose_name='图片')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sales.ProductReview', verbose_name='评价')),
            ],
            options={
                'verbose_name': '评价图片',
                'verbose_name_plural': '评价图片',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('COMPLAINT', '投诉'), ('SUGGESTION', '建议'), ('QUESTION', '咨询'), ('AFTER_SALES', '售后'), ('OTHER', '其他')], max_length=20, verbose_name='反馈类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('status', models.CharField(choices=[('PENDING', '待处理'), ('PROCESSING', '处理中'), ('RESOLVED', '已解决'), ('CLOSED', '已关闭')], default='PENDING', max_length=20, verbose_name='状态')),
                ('images', models.TextField(blank=True, verbose_name='附件图片(JSON数组)')),
                ('handle_content', models.TextField(blank=True, verbose_name='处理内容')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_feedbacks', to='app01.UserInfo', verbose_name='处理人')),
            ],
            options={
                'verbose_name': '用户反馈',
                'verbose_name_plural': '用户反馈',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_code', models.CharField(max_length=20, unique=True, verbose_name='仓库编号')),
                ('name', models.CharField(max_length=100, verbose_name='仓库名称')),
                ('address', models.TextField(verbose_name='仓库地址')),
                ('contact_person', models.CharField(max_length=50, verbose_name='联系人')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('region', models.CharField(max_length=50, verbose_name='地区')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '仓库',
                'verbose_name_plural': '仓库列表',
                'ordering': ['region', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-sort_order', '-id'], 'verbose_name': '产品', 'verbose_name_plural': '产品列表'},
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='送达时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='logistics_company',
            field=models.CharField(blank=True, max_length=50, verbose_name='物流公司'),
        ),
        migrations.AddField(
            model_name='order',
            name='logistics_info',
            field=models.TextField(blank=True, verbose_name='物流信息'),
        ),
        migrations.AddField(
            model_name='order',
            name='logistics_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='物流单号'),
        ),
        migrations.AddField(
            model_name='order',
            name='logistics_status',
            field=models.CharField(blank=True, max_length=20, verbose_name='物流状态'),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_address',
            field=models.TextField(blank=True, verbose_name='收货地址'),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='收货人'),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='收货电话'),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_region',
            field=models.CharField(blank=True, max_length=50, verbose_name='收货地区'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发货时间'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=50, verbose_name='品牌'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=50, verbose_name='产品分类'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=50, verbose_name='颜色'),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, max_length=100, verbose_name='尺寸(长x宽x高)'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否上架'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='产品编号'),
        ),
        migrations.AddField(
            model_name='product',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='重量(kg)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', '待支付'), ('PAYING', '支付中'), ('PAID', '已支付'), ('SHIPPED', '已发货'), ('DELIVERED', '已送达'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消'), ('REFUNDING', '退款中'), ('REFUNDED', '已退款')], default='PENDING', max_length=20, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='sales.Order', verbose_name='关联订单'),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='sales.Product', verbose_name='关联产品'),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='app01.UserInfo', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='productwarehouse',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='sales.Product', verbose_name='产品'),
        ),
        migrations.AddField(
            model_name='productwarehouse',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sales.Warehouse', verbose_name='仓库'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='sales.Order', verbose_name='订单'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='sales.Product', verbose_name='产品'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.UserInfo', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sales.Product', verbose_name='产品'),
        ),
        migrations.AddField(
            model_name='orderlogistics',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_tracks', to='sales.Order', verbose_name='订单'),
        ),
        migrations.AlterUniqueTogether(
            name='productwarehouse',
            unique_together={('product', 'warehouse')},
        ),
    ]
