# Generated by Django 2.1.7 on 2026-06-22 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0047_auto_20260622_1640'),
        ('sales', '0004_auto_20260622_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=100, verbose_name='商户名称')),
                ('seller_code', models.CharField(max_length=50, unique=True, verbose_name='商户编号')),
                ('payment_provider', models.CharField(choices=[('WECHAT', '微信支付'), ('ALIPAY', '支付宝'), ('BANK', '银行卡')], default='WECHAT', max_length=20, verbose_name='支付服务商')),
                ('wechat_appid', models.CharField(blank=True, max_length=64, verbose_name='微信AppID')),
                ('wechat_mchid', models.CharField(blank=True, max_length=64, verbose_name='微信商户号')),
                ('wechat_api_key', models.CharField(blank=True, max_length=128, verbose_name='微信API密钥')),
                ('wechat_cert_path', models.CharField(blank=True, max_length=500, verbose_name='微信证书路径')),
                ('wechat_key_path', models.CharField(blank=True, max_length=500, verbose_name='微信密钥路径')),
                ('alipay_app_id', models.CharField(blank=True, max_length=64, verbose_name='支付宝AppID')),
                ('alipay_private_key', models.TextField(blank=True, verbose_name='支付宝私钥')),
                ('alipay_public_key', models.TextField(blank=True, verbose_name='支付宝公钥')),
                ('alipay_gateway', models.CharField(blank=True, default='https://openapi.alipay.com/gateway.do', max_length=200, verbose_name='支付宝网关')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='银行名称')),
                ('bank_account_name', models.CharField(blank=True, max_length=100, verbose_name='开户名')),
                ('bank_account_number', models.CharField(blank=True, max_length=50, verbose_name='银行卡号')),
                ('bank_branch', models.CharField(blank=True, max_length=200, verbose_name='开户行')),
                ('withdraw_min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='最低提现金额')),
                ('withdraw_commission', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='提现手续费率')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to='app01.UserInfo', verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '卖家/商户',
                'verbose_name_plural': '卖家/商户列表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='支付平台交易号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='收货人'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='产品编号'),
        ),
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sales.Seller', verbose_name='卖家'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.Seller', verbose_name='卖家'),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sales.Seller', verbose_name='卖家'),
            preserve_default=False,
        ),
    ]
