# Generated by Django 2.1.7 on 2025-11-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LessonProjectME', '0005_auto_20210422_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testprojectll',
            name='Customer',
            field=models.CharField(choices=[('', ''), ('C38(NB)', 'C38(NB)'), ('C38(NB)-SMB', 'C38(NB)-SMB'), ('C38(AIO)', 'C38(AIO)'), ('T88(AIO)', 'T88(AIO)'), ('T89', 'T89'), ('A39', 'A39'), ('C85', 'C85'), ('Others', 'Others')], max_length=20, verbose_name='Customer'),
        ),
    ]
